name: sls-pipeline-prod
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  Deploy_to_GCP_SLS:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: npm install
        run: npm install
      - name: Decrypt secret
        run: ./.github/scripts/decrypt_secret_prod.sh
        env:
          SECRET_PASSPHRASE: ${{ secrets.SECRET_PASSPHRASE }}    
      - name: Validate GCP Cloud Function
        uses: serverless/github-action@master
        with:
          args: package --stage prod
        env:
          CREDENTIALS_PATH: /github/workspace/secrets/keyfile_dev.json
      - name: Deploy GCP Cloud Function
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        uses: serverless/github-action@master
        with:
          args: deploy --stage prod
        env:
          CREDENTIALS_PATH: /github/workspace/secrets/keyfile_prod.json