name: sls-pipeline-dev
on:
  push:
    branches:
      - develop
      - main
  pull_request:
    branches:
      - develop
      - main

jobs:
  Deploy_to_GCP_SLS:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: npm install
        run: npm install
      - name: Decrypt secret
        run: ./.github/scripts/decrypt_secret_dev.sh
        env:
          SECRET_PASSPHRASE: ${{ secrets.SECRET_PASSPHRASE }}    
      - name: Validate GCP Cloud Function
        uses: serverless/github-action@master
        with:
          args: package
        env:
          CREDENTIALS_PATH: /github/workspace/secrets/keyfile.json
      - name: Deploy GCP Cloud Function
        #if: github.ref == 'refs/heads/develop' && github.event_name == 'push'
        uses: serverless/github-action@master
        with:
          args: deploy
        env:
          CREDENTIALS_PATH: /github/workspace/secrets/keyfile_dev.json